<?php

/*
+-----------------------------------------------------------------------+
| language/ru_RU/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['userinfo'] = 'Информация о пользователе';
$labels['imapserver'] = 'Сервер IMAP';
$labels['smtpserver'] = 'Сервер SMTP';
$labels['port'] = 'Порт';
$labels['created'] = 'Создан';
$labels['lastlogin'] = 'Последний вход';
$labels['defaultidentity'] = 'Default Identity';
$labels['dateformat'] = 'Формат даты';
$labels['back'] = 'Назад';

?>